### ISSUE TITLE
"GimbalController" is not defined

### ISSUE THREAD

**Issue by hectorri** [waveshareteam/ugv_rpi#2]
There is a reference to "GimbalController" on base_ctrl.py.

```
	if __name__ == '__main__':
	import time

	gimbal = GimbalController('/dev/serial0', 115200)
	gimbal.gimbal_lights_ctrl(255, 0)

	while True:
		try:
			gimbal.gimbal_ctrl(-90, 0, 0, 0)
			time.sleep(2)
			gimbal.gimbal_ctrl(90, 60, 0, 0)
			time.sleep(2)
		except:
			pass

	gimbal.gimbal_dev_close()
```

Where is GimbalController?

Thanks in advance.

**Comment by EffectsMachine** [comment]
functions for gimbal-ctrl were moved into the BaseController class, I'll update the code inside if __name__ == '__main__' later.

**Comment by EffectsMachine** [comment]
Hi, it's updated
if __name__ == '__main__':
	# RPi5
	base = BaseController('/dev/ttyAMA0', 115200)

	# RPi4B
	# base = BaseController('/dev/serial0', 115200)

	# breath light for 15s
	base.breath_light(15)

	# gimble ctrl, look forward
	#                x  y  spd acc
	base.gimbal_ctrl(0, 0, 10, 0)
